### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by synaptiko** [WebReflection/viper-news#8]
I cloned this repository and ran `npm install` and then `npm run build` but it failed. I also noticed that `package-lock.json` was changed.

Here's the output from the command:
```
λ npm run build

> viper-news@0.0.0 build /home/eggze/Projects/viper-news
> npm run generate-views && npm run generate-css && webpack && npm run babel && npm run sw


> viper-news@0.0.0 generate-views /home/eggze/Projects/viper-news
> bash ./bash/generate-views


> viper-news@0.0.0 generate-css /home/eggze/Projects/viper-news
> bash ./bash/generate-css

Hash: 3bd938fd0f4425365670
Version: webpack 3.10.0
Time: 69ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.93 kB       0  [emitted]  client
   [0] ./client/js/index.js 2.44 kB {0} [built] [failed] [1 error]

ERROR in ./client/js/index.js
Module build failed: Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/eggze/Projects/viper-news/node_modules/babel-loader/lib/index.js:3:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at loadLoader (/home/eggze/Projects/viper-news/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/eggze/Projects/viper-news/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/eggze/Projects/viper-news/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/home/eggze/Projects/viper-news/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/home/eggze/Projects/viper-news/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/home/eggze/Projects/viper-news/node_modules/webpack/lib/Compilation.js:151:10)
    at moduleFactory.create (/home/eggze/Projects/viper-news/node_modules/webpack/lib/Compilation.js:456:10)
    at factory (/home/eggze/Projects/viper-news/node_modules/webpack/lib/NormalModuleFactory.js:241:5)
    at applyPluginsAsyncWaterfall (/home/eggze/Projects/viper-news/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
    at /home/eggze/Projects/viper-news/node_modules/webpack/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/home/eggze/Projects/viper-news/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/eggze/Projects/viper-news/node_modules/webpack/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/home/eggze/Projects/viper-news/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/home/eggze/Projects/viper-news/node_modules/webpack/lib/NormalModuleFactory.js:194:7)
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

**Comment by synaptiko** [comment]
Installation of babel-core and babel-loader fixed the issue.
`npm install babel-core babel-loader --save-dev`
